# 本地路径配置
local:
  path:

# 远端对象存储配置
remote:
  endpoint: cos.ap-guangzhou.myqcloud.com # 例如：cos.ap-guangzhou.myqcloud.com
  use_ssl: true
  secret_id: ${MY_SECRET_ID} # 可设置在环境变量中
  secret_key: ${MY_SECRET_KEY} # 可设置在环境变量中
  bucket:
  region:
  path:

# 同步配置
sync:
  # 是否启用实时同步（监听本地文件变更进行同步，仅同步服务运行期间发生变更的文件，可结合check_job实现全量同步）
  real_time:
    enable: false
    hot_delay: 5 # 单位分钟（1-60），对频繁修改的文件进行延迟同步，避免频繁的覆盖上传
  # 是否启用定期文件对账（扫描对比本地与远端文件差异进行同步）
  check_job:
    enable: true
    interval: 72 # 文件对账频率间隔，单位小时
    start_at: 4:00:00 # 文件对账启动时间（建议选在凌晨），将结合频率间隔配置定期执行
  # 忽略不同步的文件和文件夹
  ignore:
    - .*.swp
    - "*~"
    - .DS_Store
    - .ds_store
    - .svn
    - .git
    - Thumbs.db
    - .idea
log:
  - writer: console
    formatter: console
    level: DEBUG
  - writer: file
    formatter: json
    level: DEBUG
    format_config:
      time_fmt: "2006-01-02 15:04:05.000"
    write_config:
      log_path: "./run.log"
      max_size: 10
      max_age: 30
      compress: true
